CREATE TABLE Curso (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    creditos INT NOT NULL
);

CREATE TABLE NRC (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(10) NOT NULL,
    docente VARCHAR(150) NOT NULL,
    modalidad VARCHAR(100) NOT NULL,
    es_principal BOOLEAN NOT NULL,

    -- llaves foraneas
    curso_id BIGINT NOT NULL,
    nrc_vinculado_id BIGINT,

    FOREIGN KEY (curso_id) REFERENCES Curso(id),
    FOREIGN KEY (nrc_vinculado_id) REFERENCES NRC(id)
);


CREATE TABLE BloqueHorario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dia VARCHAR(50) NOT NULL CHECK (dia IN ('LUNES', 'MARTES', 'MIERCOLES' , 'JUEVES' , 'VIERNES' , 'SABADO' , 'DOMINGO')),
    hora_inicio TIME NOT NULL,
    hora_fin TIME NOT NULL,
    aula VARCHAR(50) NOT NULL,

    -- llaves fonareas
    nrc_id BIGINT NOT NULL,

    FOREIGN KEY (nrc_id) REFERENCES NRC(id)

);